### ISSUE TITLE
manuelles Anstoßen des Kalibriervorgangs ermöglichen

### ISSUE THREAD

**Issue by floergri** [binsim/postmelder#53]
- über physischen button oder über Webinterface+MQTT
- Schritte (zuerst kein Gewicht und dann bekanntes Gewicht auflegen) dem User zeigen
- Usereingabe von bekanntem Gewicht ermöglichen oder festes Kalibrierungsgewicht (z.B. 270g Rollen) definieren

**Comment by binsim** [comment]
Die Kommunikation wird entsprechend aufgebaut:

<img width="489" alt="Kommunikationsablauf" src="https://github.com/binsim/postmelder/assets/64983699/871424fc-a1ec-44a8-b8bf-945fe8d46579">
