### ISSUE TITLE
Zeitformat des Raspberry Pi's ändern

### ISSUE THREAD

**Issue by binsim** [binsim/postmelder#76]
Ändern des lokalen Zeitformats ermöglich, sodass auch andere Formatierungen in der E-Mail Benachrichtigung möglich sind.

Dies könnte entweder 
- direkt in Docker ermöglicht werden, dann ist es im späteren Verlauf nicht mehr änderbar oder 
- über die Website, dann könnte man dies im späteren Verlauf noch ändern, wäre aber auch ein größerer Aufwand oder
- für jede E-Mail Benachrichtigung (wie die E-Mail selbst) im Konfigurationsfenster vom ESP-Device

was meint ihr?

Aktuell ist das Zeitformat das default in Docker, was Englisch sein müsste oder das Zeitformat des Docker-Hosts, das weiß ich nicht genau

**Comment by floergri** [comment]
denke, dass harcoden auf europäisches Format ausreicht

**Comment by binsim** [comment]
Die Zeitzone kann man in der `.yml` Datei mit ändern
`ENV TZ="Africa/Lusaka"`
